# Generated by Django 2.2.14 on 2020-11-29 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignature', models.CharField(default='', max_length=100)),
                ('period', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('estudiante', models.ManyToManyField(related_name='Clase', to='estudiantes.Estudiante')),
                ('profesor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Clase', to='profesores.Profesor')),
            ],
        ),
    ]
