# Generated by Django 2.2.14 on 2020-12-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_auto_20201129_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='estudiante',
            field=models.ManyToManyField(null=True, related_name='Clase', to='estudiantes.Estudiante'),
        ),
    ]
