# Generated by Django 2.2.14 on 2020-11-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('idNumber', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('approved', models.BooleanField(null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
