# Generated by Django 2.2.14 on 2020-11-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
